language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh && opam install oasis && oasis setup && make configure CONFIGUREFLAGS=--enable-tests # && make test
env:
  global:
    - PACKAGE=my-package
    # - PACKAGE=lambda-rti
  matrix:
    # - OCAML_VERSION=4.03
    # - OCAML_VERSION=4.04
    # - OCAML_VERSION=4.05
    - OCAML_VERSION=4.06
os:
  # - linux
  - osx